# Generated by Django 3.1.7 on 2021-03-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210329_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
