# Generated by Django 3.1.7 on 2021-03-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='principal_img'),
        ),
    ]
