# Generated by Django 3.1.7 on 2021-03-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='product',
        ),
        migrations.AddField(
            model_name='feature',
            name='product',
            field=models.ManyToManyField(to='demo.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Cubrebocas'), (2, 'Batas'), (3, 'Botas'), (4, 'Gorros'), (5, 'Insumos')]),
        ),
    ]
