# Generated by Django 3.1.7 on 2021-04-07 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0008_auto_20210330_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_1', models.CharField(max_length=10, null=True, verbose_name='Teléfono o número de celular')),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón social')),
                ('rfc', models.CharField(blank=True, max_length=50, null=True, verbose_name='RFC')),
                ('direccion_fiscal', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección fiscal')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('tel_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de facturación')),
                ('correo_fact', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de facturación')),
                ('cfdi', models.CharField(blank=True, max_length=50, null=True, verbose_name='CFDI')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección')),
                ('municipio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('cp', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código Postal')),
                ('numero_ext', models.IntegerField(blank=True, null=True, verbose_name='Número exterior')),
                ('numero_int', models.IntegerField(blank=True, null=True, verbose_name='Número interior')),
                ('entre_calle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Entre calle')),
                ('entre_calle_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Y calle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
