# Generated by Django 3.1.7 on 2021-04-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20210407_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estado_fact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
