# Generated by Django 3.2 on 2021-04-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_car_compra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Carrito',
        ),
    ]
