# Generated by Django 3.2 on 2021-04-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_carrito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='status',
            field=models.IntegerField(choices=[('PAGADO', 0), ('ACTIVO', 1), ('ELIMINADO', 2)], default=1),
        ),
    ]
