# Generated by Django 3.2 on 2021-04-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_carrito_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='status',
            field=models.IntegerField(choices=[('PAGADO', 0), ('ACTIVO', 1)], default=1),
        ),
        migrations.CreateModel(
            name='Image_collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='principal_img/collection')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.product', verbose_name='Producto')),
            ],
        ),
    ]
