# Generated by Django 3.2 on 2021-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_auto_20210422_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='compra',
            name='status_compra',
            field=models.IntegerField(
                choices=[('EN_PROCESO', 0), ('ENVIANDO', 1), ('ENTREGADO', 2)], default=0),
        ),
    ]
