# Generated by Django 3.2 on 2021-05-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_alter_compra_fecha_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateTimeField(),
        ),
    ]
