# Generated by Django 3.2 on 2021-05-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_alter_compra_fecha_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fecha_compra',
        ),
    ]
