# Generated by Django 3.2 on 2021-05-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_alter_compra_status_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='renglonCarrito',
        ),
        migrations.AddField(
            model_name='carrito',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='paqueteria',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status_compra',
            field=models.IntegerField(choices=[('EN_PROCESO', 0), ('ENVIANDO', 1), ('ENTREGADO', 2)], default=0),
        ),
    ]
