# Generated by Django 3.2 on 2021-05-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0022_auto_20210504_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status_compra',
            field=models.IntegerField(choices=[('EN_PROCESO', 0), ('ENTREGADO', 1)], default=0),
        ),
    ]
