# Generated by Django 3.2 on 2021-05-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0024_auto_20210506_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.compra'),
        ),
    ]
